apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingress-controller-svc-reader
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: infoblox-dns-webhook-cert-signer
rules:
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificates
  - certificatesigningrequests
  verbs:
  - get
  - list
  - create
  - delete