apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingress-controller-svc-reader
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
