apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: infoblox-secrets-services-reader-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infoblox-secrets-services-reader
subjects:
- kind: ServiceAccount
  name: {{ include "infoblox-dns-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: infobloxdns-webhook-updator-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infobloxdns-webhook-updator
subjects:
- kind: ServiceAccount
  name: {{ include "infoblox-dns-webhook.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---

