---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.project.name }}-ingress-mutation
webhooks:
  - name: {{ .Values.project.name }}.mutation.{{ .Release.Namespace }}.svc
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: [ "kube-system", "vmware-system-auth", "vmware-system-cloud-provider", "vmware-system-csi", "{{ .Release.Namespace }}" ]
    rules:
      - operations: [ "CREATE", "UPDATE", "DELETE" ]
        apiGroups: [ "networking.k8s.io" ]
        apiVersions: [ "v1" ]
        resources: [ "ingresses" ]
        scope: "Namespaced"
    clientConfig:
      caBundle: {{ .Values.tls.cert }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.project.name }}
        path: "/mutate"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 30
