---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infobloxInfo.secret.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.infobloxInfo.secret }}
  INFOBLOX_{{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
type: tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
---