---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infobloxInfo.secret.name | quote }}
type: Opaque
data:
  {{- range $key, $val := .Values.infobloxInfo.secret }}
  INFOBLOX_{{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
  namespace: {{ .Release.Namespace | quote }}
type: tls
data: 
{{ ( include "infoblox-dns-webhook.gen-cert" . ) | indent 2 }}
---
