---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infobloxInfo.secret.name }}
type: Opaque
data:
  {{- range $key, $val := .Values.infobloxInfo.secret }}
  INFOBLOX_{{ $key | upper }}: {{ $val | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
type: tls
data:
  tls.crt: {{ .Values.tls.cert }}
  tls.key: {{ .Values.tls.key }}
---
{{- $tlscert := genSelfSignedCert "{{ .Values.tls.certCommonName }}.{{ .Release.Namespace }}" 365 }}
apiVersion: v1
kind: Secret
metadata:
  #name: {{ .Values.tls.name | quote }}
  name: {{ .Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tlscert.Cert | b64enc | quote }}
  tls.key: {{ $tlscert.Key | b64enc | quote }}
{{- end }}