name: Release Infoblox Webhook Charts
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.HELM_TOKEN }}
          number: 1
          method: squash # merge rebase
          repo: middlewaregruppen/helm-charts

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.8.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.HELM_TOKEN }}"